# Generated by Django 5.2.3 on 2025-06-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=255)),
                ('anio_fundacion', models.IntegerField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa/')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('codigo_empleado', models.CharField(max_length=50)),
                ('otros_datos', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='trabajadores/')),
            ],
        ),
    ]
