# Generated by Django 5.2.3 on 2025-06-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=255)),
                ('anio_fundacion', models.IntegerField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa/')),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cedula',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='otros_datos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='codigo_empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
