# Generated by Django 5.2.3 on 2025-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('año_fundacion', models.PositiveIntegerField()),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresa/')),
            ],
        ),
    ]
